feat(models-user-profile)[skp-290]: Fix on creating UserProfile  Soci…
ppm-jew9207/PPM-back-end-nest-js pull request #124
Opened 2020-09-29 18:32 UTC by Gardemarin

…alLinks  issue.

2020-09-29 19:25 UTC, doncevas requested changes

2020-09-29 19:25 UTC, doncevas commented on apps/api/src/app/domains/userProfiles/commands/create-user-profile.command.ts
> +    if (data.socialLinks[0] == null) {
if you want to check or array got null you should check like this: data.socialLinks.includes(null)

2020-09-30 18:08 UTC, karolisracas approved these changes

2020-09-30 19:35 UTC, doncevas requested changes

2020-09-30 19:35 UTC, doncevas commented on apps/api/src/app/domains/userProfiles/commands/create-user-profile.command.ts
> +      data.socialLinks = [];
throw BadRequest if pass this condition

2020-10-01 18:58 UTC, doncevas approved these changes

2020-10-01 18:58 UTC, merged