padaryta 1 is 3
ppm-jew9207/PPM-back-end-nest-js pull request #186
Opened 2021-01-26 19:45 UTC by edichkas

Push'inu ,ka esu siam momentui padares, ir kad nepamirst, kaip veikia git :)
Nesu tikras ar teisingai darau:
Ikeliau mygtukus, Idejau viena funkcija mygtuku isjungimui
Liko:
realizuoti componentu iskvetima po mygtuku paspaudimo
Testai

2021-01-28 19:26 UTC, edichkas commented
sugeneruotas storybook

2021-01-28 19:34 UTC, doncevas requested changes

2021-01-28 19:34 UTC, doncevas commented on libs/shared/adverts-add-buttons/src/lib/shared-adverts-add-buttons.tsx
> +  /*
you should add return events for add and cancel buttons

2021-02-01 21:11 UTC, doncevas approved these changes

2021-02-01 21:12 UTC, merged