feat(features/mentors): [skp-430] preview of all mentors
ppm-jew9207/PPM-back-end-nest-js pull request #234
Opened 2021-05-10 08:13 UTC by Neutronas

2021-05-11 18:59 UTC, doncevas requested changes

2021-05-11 18:59 UTC, doncevas commented on libs/features/mentors/src/lib/features-mentors.tsx
> +        {mentors.list.length &&
what happen if return empty array?

2021-05-17 07:17 UTC, Neutronas commented on libs/features/mentors/src/lib/features-mentors.tsx
> +        {mentors.list.length &&
Line 30 is checking that

2021-05-17 18:54 UTC, doncevas approved these changes

2021-05-17 18:54 UTC, merged