feat(be/courses): [skp-453] courses paging and count
ppm-jew9207/PPM-back-end-nest-js pull request #266
Opened 2021-09-13 18:55 UTC by Neutronas

2021-09-15 07:06 UTC, doncevas requested changes

2021-09-15 07:06 UTC, doncevas commented on apps/api/src/app/models/courses/courses.service.ts
> +    if (String(params.count) === 'true') {
same as above

2021-09-15 14:44 UTC, Neutronas commented on apps/api/src/app/models/courses/courses.service.ts
> +    if (String(params.count) === 'true') {
it's boolean in swagger but swagger still returns text instead.

2021-09-28 19:02 UTC, doncevas approved these changes

2021-09-28 19:02 UTC, merged