feat(snack-bar): [skp-246} create system messages feature
ppm-jew9207/PPM-back-end-nest-js pull request #91
Opened 2020-08-18 20:36 UTC by doncevas

2020-08-19 19:19 UTC, karolisracas commented on apps/ppm/src/app/app.scss
> +  font-size: 16px;
should we use REM instead of px?

2020-08-20 09:31 UTC, Gardemarin requested changes

2020-08-20 09:31 UTC, Gardemarin commented on libs/features/registration/src/lib/features-registration.tsx
> +    console.log(stepIndex);
![pataisyk](https://user-images.githubusercontent.com/24617345/90751862-8faf6b80-e2ce-11ea-8f81-1541c13284cd.png)

2020-08-24 07:46 UTC, Gardemarin requested changes

2020-08-24 07:46 UTC, Gardemarin commented on libs/data-access/authorization/src/lib/saga.ts
> +    if(result && result.success === false){
```result && result.success === false``` change to ```result && !result.success```

2020-08-24 13:48 UTC, Gardemarin approved these changes

2020-08-24 13:55 UTC, merged