fix(libs-shared): [skp 231] left side menu fixes
ppm-jew9207/PPM-back-end-nest-js pull request #98
Opened 2020-08-27 18:48 UTC by SimasKir

2020-08-27 18:53 UTC, doncevas requested changes

2020-08-27 18:53 UTC, doncevas commented on libs/shared/left-side-menu/src/lib/shared-left-side-menu.scss
> +.MuiDrawer-paper {
don't rewrite material ui classes, you should set your own style or class in editable component

2020-08-29 13:37 UTC, Gardemarin approved these changes

2020-09-02 13:16 UTC, doncevas approved these changes

2020-09-02 13:16 UTC, merged